### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by lbdroid** [gabrielgagz/android_device_razer_pearlyn#3] opened 2017-08-14 14:58 UTC
Did you make any changes to your build tree compared to what would be pulled in with lineage's 14.1 default manifest + your local manifest?

It doesn't build for me unless I make a few changes;

1) ninja: error: 'NOTICE-TARGET-STATIC_LIBRARIES-libbootloader_message', needed by '/mnt/data/LOSP712/out/target/product/pearlyn/root/init', missing and no known rule to make it
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
Hackaround: comment out everything below the "#TWRP" heading in BoardConfig.mk

2) (1) causes recovery.img to be bigger than the partition size.
Hackaround: increase BOARD_RECOVERYIMAGE_PARTITION_SIZE

(1) and (2) obviously causes the generated recovery.img to be useless.

3) An invalid conversion error in hardware/qcom/media-caf/apq8084/mm-video-v4l2/test
Hackaround: disable building test by commenting it out of the Android.mk

**Comment by gabrielgagz** [comment] 2017-08-14 15:14
1. I'm using twrp as default recovery. LOS recovery is obsolete. The big main problem with the recovery is the size of the partition. That's why we need a custom mkbootimg (with lzma support), and a usable recovery.
Best solution: under 'bootable' dir, git clone https://github.com/omnirom/android_bootable_recovery recovery-twrp
Hackaround: As you post, increase BOARD_RECOVERYIMAGE_PARTITION_SIZE and build an obsolete recovery.

2. I submit 2 patches to LOS gerrit, both was rejected, but they solve 2 of 3 build errors.
https://review.lineageos.org/#/c/182329/
https://review.lineageos.org/#/c/182331/
And this probably is breaking your build: https://review.lineageos.org/#/c/182412/1/mm-video-v4l2/vidc/test/msm_vidc_test.c (Still not solved on lineage)

Let me know if you encounter extra problem. But i think this is all. As you see is not our problem, mostly come from outdated caf sources on Lineage.

When you have a flashable build, and you intall in your device another problem will come related to signature mismatch with some packages, specially Bluetooth. No solution yet. There is a "hackish" workaround, as you can read here: https://groups.google.com/forum/#!topic/android-building/92h9KhL2JDY wich works, but isn't a proper solution.

**Comment by gabrielgagz** [comment] 2017-08-14 15:28
Another thing, you need https://github.com/LineageOS/android_device_qcom_common
Probably i should include this in the manifest also.

**Comment by lbdroid** [comment] 2017-08-14 15:36
You can also add the recovery-twrp into the local manifest.

**Comment by lbdroid** [comment] 2017-08-14 15:45
For bluetooth, you can try adding "LOCAL_PRIVILEGED_MODULE := true" to packages/apps/Bluetooth/Android.mk below the line "LOCAL_PACKAGE_NAME := Bluetooth", which should move the application from /system/app/ to /system/priv-app/ and bypass the signature problem.

**Comment by gabrielgagz** [comment] 2017-08-14 15:51
Yes, but  my main idea is not mess around with the original LOS code. That's why i submit the patches.

**Comment by lbdroid** [comment] 2017-08-14 15:59
When the alternative is "return PackageManager.SIGNATURE_MATCH;" hack, you're still messing with the original code.

Also in my experience, you probably won't get too far trying to get them to fix broken code. Unless everybody in charge there has been replaced in the last 4 years, they're a pretty obtuse bunch.

**Comment by gabrielgagz** [comment] 2017-08-14 16:11
A hack is a hack, is not an alternative. Right now i'm using the rom with BT broken...until i found a proper solution. Regarding to LOS Team, they are pretty accesible, but gerrit is a pain in the ass...

**Comment by lbdroid** [comment] 2017-08-14 19:25
Hmm, very curious....
The CERT.RSA file in Bluetooth.apk and BluetoothExt.apk DO NOT MATCH.
These two packages have a shared user.
Hence the signature mismatch error.

Try wiping the line in common_mini_tv.mk for BluetoothExt. That package (despite being listed under "Required CM packages" is most definitely NOT required.

It may also require a wipe before the error clears.

**Comment by lbdroid** [comment] 2017-08-14 20:20
https://android.googlesource.com/platform/frameworks/base/+/4f868ed/services/core/java/com/android/server/pm/PackageManagerService.java#5495

This code shouldn't even run unless you are doing a system upgrade. This feels like something that should be resolved by a factory reset.

**Comment by lbdroid** [comment] 2017-08-14 20:42
Alternative to rebuilding the system image is to rm -rf /system/app/BluetoothExt, then run a factory reset.

**Comment by lbdroid** [comment] 2017-08-14 20:55
There are a bunch of other packages in /vendor/qcom that use the shared userid android.uid.bluetooth.
The thing about shared user signatures is that the FIRST package to install with that user WINS. I also have a vague recollection of being limited to 2 packages per userid, although that could only apply to user installed applications rather than system applications.

**Comment by lbdroid** [comment] 2017-08-14 21:17
Question: why are you doing this;
$(call inherit-product, device/razer/pearlyn/common_mini_tv.mk)

and not
$(call inherit-product, vendor/cm/config/common_mini_tv.mk)

**Comment by gabrielgagz** [comment] 2017-08-14 21:57
`07-29 18:38:34.669  1501  1606 W PackageManager: Failed to parse /system/app/BluetoothExt: Signature mismatch for shared user: SharedUserSetting{3709c7f android.uid.bluetooth/1002}
07-29 18:38:34.719  1501  1605 W PackageManager: Failed to parse /system/app/Bluetooth: Signature mismatch for shared user: SharedUserSetting{3709c7f android.uid.bluetooth/1002}
07-29 18:38:34.849  1501  1605 W PackageManager: Failed to parse /system/app/BugReportSender: Signature mismatch for shared user: SharedUserSetting{fa09f2a android.uid.shell/2000}`

This are the package who fails due to signature mismatch. Believe me, i try all with no luck. I'll try not building BluetoothExt. 

> Question: why are you doing this;
>$(call inherit-product, device/razer/pearlyn/common_mini_tv.mk)
>
>and not
>$(call inherit-product, vendor/cm/config/common_mini_tv.mk)

In thiss commit i did the change: https://github.com/gabrielgagz/android_device_razer_pearlyn/commit/623890cb7a3da4e83d31a89fc19b605b678a2311

I don't want to build packages like Trebuchet, Eleven, Jelly, ExactCalculator, etc...wich are obsolets in Android TV. So i copy the file and i did my own version.Probably exists a better and more elegant solution to do this...i don't know...

**Comment by gabrielgagz** [comment] 2017-08-14 22:36
Another thing i forgot to mention. The hardware/qcom/display-caf/apq8084/libhdmi/libhdmi.cpp goes to 4k:

`EDIDData gEDIDData [] = {
    EDIDData(HDMI_VFRMT_1440x480i60_4_3, 1440, 480, 60, 1),
    EDIDData(HDMI_VFRMT_1440x480i60_16_9, 1440, 480, 60, 2),
    EDIDData(HDMI_VFRMT_1440x576i50_4_3, 1440, 576, 50, 3),
    EDIDData(HDMI_VFRMT_1440x576i50_16_9, 1440, 576, 50, 4),
    EDIDData(HDMI_VFRMT_1920x1080i60_16_9, 1920, 1080, 60, 5),
    EDIDData(HDMI_VFRMT_640x480p60_4_3, 640, 480, 60, 6),
    EDIDData(HDMI_VFRMT_720x480p60_4_3, 720, 480, 60, 7),
    EDIDData(HDMI_VFRMT_720x480p60_16_9, 720, 480, 60, 8),
    EDIDData(HDMI_VFRMT_720x576p50_4_3, 720, 576, 50, 9),
    EDIDData(HDMI_VFRMT_720x576p50_16_9, 720, 576, 50, 10),
    EDIDData(HDMI_VFRMT_800x600p60_4_3, 800, 600, 60, 11),
    EDIDData(HDMI_VFRMT_848x480p60_16_9, 848, 480, 60, 12),
    EDIDData(HDMI_VFRMT_1024x768p60_4_3, 1024, 768, 60, 13),
    EDIDData(HDMI_VFRMT_1280x1024p60_5_4, 1280, 1024, 60, 14),
    EDIDData(HDMI_VFRMT_1280x720p50_16_9, 1280, 720, 50, 15),
    EDIDData(HDMI_VFRMT_1280x720p60_16_9, 1280, 720, 60, 16),
    EDIDData(HDMI_VFRMT_1280x800p60_16_10, 1280, 800, 60, 17),
    EDIDData(HDMI_VFRMT_1280x960p60_4_3, 1280, 960, 60, 18),
    EDIDData(HDMI_VFRMT_1360x768p60_16_9, 1360, 768, 60, 19),
    EDIDData(HDMI_VFRMT_1366x768p60_16_10, 1366, 768, 60, 20),
    EDIDData(HDMI_VFRMT_1440x900p60_16_10, 1440, 900, 60, 21),
    EDIDData(HDMI_VFRMT_1400x1050p60_4_3, 1400, 1050, 60, 22),
    EDIDData(HDMI_VFRMT_1680x1050p60_16_10, 1680, 1050, 60, 23),
    EDIDData(HDMI_VFRMT_1600x1200p60_4_3, 1600, 1200, 60, 24),
    EDIDData(HDMI_VFRMT_1920x1080p24_16_9, 1920, 1080, 24, 25),
    EDIDData(HDMI_VFRMT_1920x1080p25_16_9, 1920, 1080, 25, 26),
    EDIDData(HDMI_VFRMT_1920x1080p30_16_9, 1920, 1080, 30, 27),
    EDIDData(HDMI_VFRMT_1920x1080p50_16_9, 1920, 1080, 50, 28),
    EDIDData(HDMI_VFRMT_1920x1080p60_16_9, 1920, 1080, 60, 29),
    EDIDData(HDMI_VFRMT_1920x1200p60_16_10, 1920, 1200, 60, 30),
    EDIDData(HDMI_VFRMT_2560x1600p60_16_9, 2560, 1600, 60, 31),
    EDIDData(HDMI_VFRMT_3840x2160p24_16_9, 3840, 2160, 24, 32),
    EDIDData(HDMI_VFRMT_3840x2160p25_16_9, 3840, 2160, 25, 33),
    EDIDData(HDMI_VFRMT_3840x2160p30_16_9, 3840, 2160, 30, 34),
    EDIDData(HDMI_VFRMT_4096x2160p24_16_9, 4096, 2160, 24, 35),
};`

I only own 1080p tv's. But hdmi_edid doesn't seems to work properly in my case...
When i boot the device with all the modes enabled...i got black screen because my tv (or the Forge) insist to go always to max resolution. So, for now, my dirty solution is remove all the modes over 1920x1080@60. According o qualcomm the Snapdragon 805 is 4k capable:

https://www.qualcomm.com/products/snapdragon/processors/805
https://en.wikipedia.org/wiki/Extended_Display_Identification_Data
https://github.com/gabrielgagz/android_kernel_razer_pearlyn/blob/cm-14.1/drivers/video/msm/mdss/rzr_hdmiedid.c

**Comment by lbdroid** [comment] 2017-08-15 12:38
I haven't looked at the code yet, but it seems to me that if it is pulling the data from an array, then it is obviously not obtaining that data from the monitor.

**Comment by lbdroid** [comment] 2017-08-15 12:43
The rzr_hdmiedid.c is hugely inadequate. It reads only vendor name, product name, week of manufacture, and year of manufacture. It would probably be best to replace it with something that is more complete.

**Comment by lbdroid** [comment] 2017-08-15 12:50
https://github.com/gabrielgagz/android_kernel_razer_pearlyn/blob/cm-14.1/drivers/video/msm/mdss/mdss_hdmi_edid.c#L1471

So what it looks like its doing, is overwriting the edid buffer with razer's version which doesn't contain anything about the monitor's actual modes.

I'd try to comment out that line and see what happens.

**Comment by gabrielgagz** [comment] 2017-08-15 12:51
The data is there, as you say, inadequate, but is there. The device need this file or a better replacement, without this for example, hdcp breaks. But do your own test, i'll try to get rid of this with no luck yet...

**Comment by lbdroid** [comment] 2017-08-15 12:55
No, its way dumber than that. That rzr file does absolutely NOTHING. It just prints out a line to the kmsg.

**Comment by lbdroid** [comment] 2017-08-15 12:58
Ugh, it doesn't even do that. I think its incomplete.

**Comment by gabrielgagz** [comment] 2017-08-15 13:11
The info goes to /proc/hdmi_edid_info
Razer loves /proc file system...

**Comment by lbdroid** [comment] 2017-08-15 13:19
But it creates that entry itself, it isn't standard. What reads it?

**Comment by lbdroid** [comment] 2017-08-15 13:43
The answer is NOTHING. I grepped through my entire build tree and the only place where the string "hdmi_edid_info" appears, is in rzr_hdmiedid.c.

**Comment by gabrielgagz** [comment] 2017-08-15 14:16
Nothing is standard with Razer. The old led layer (wich i remove) also is managed via /prc/led_device in stock.
This doesn't work at all in Lineage. Exists a service in stock wich i cant find or implement in this new rom (ctrlled), probably is a property service i don't know...just don care.

Regarding to proc also we have /proc/usb_device wich handles the "Device Mode" (debug mode) of the usb port. The stock config of Lineage (Usb debugging) doesn't seems to handle this, but this vendor driver does. If you echo > 0 to the file you enable the "Device Mode" and if you echo > 1 you enable the "host Mode". This works so probably we have to add a new entry in setting or redirect this function to stock...

Also exists the "razerfilter" driver wich seems related to the Serval probably, but i didn't take a look yet...

**Comment by lbdroid** [comment] 2017-08-15 14:25
The point isn't that it isn't standard, the point is that you can write anything you want to something that NOTHING reads, and it won't make any difference at all. There is nothing ANYWHERE that reads hdmi_edid_info, at least not in LOS source code. There may very well have been something in the razer hacked hardware/display code, but we don't have source for that, which means that this file rzr_hdmiedid.c is useless for us.

**Comment by lbdroid** [comment] 2017-08-15 14:29
I believe that mEDIDModes[] is supposed to be filled in with the display's ACTUAL edid modes. It is then supposed to scan through it for the highest "order", and select that to actually use.

**Comment by lbdroid** [comment] 2017-08-15 14:44
The kernel is supposed to write out the edid modes to /sys/devices/virtual/graphics/fbX/edid_modes

Can you run this?
cat /dev/kmsg | grep "readResolution\|openDeviceNode"

Also make sure that permissions on that file are OK, and that your sepolicy allows access to it.

**Comment by gabrielgagz** [comment] 2017-08-15 14:53
I'm working right now...i'll be in home in 5 hours, and sure i'll post the result of that command...

**Comment by lbdroid** [comment] 2017-08-15 15:15
Sorry, that won't be in kmsg. It will be in logcat.

**Comment by lbdroid** [comment] 2017-08-15 15:35
This is pretty weird. It doesn't look like it is actually handling EDID data at all, rather from edid_modes, it is just reading a comma separated list of numbers (ascii), like "16,4,5,3,32,34,1".

Those numbers in the list are an index to the array gEDIDData.

I suspect that the problem is that the indices in the kernel don't match the indices in hardware/display/

**Comment by lbdroid** [comment] 2017-08-15 15:55
Yep, that's it.
Take a look at kernel/include/uapi/video/mdm_hdmi_modes.h
#define HDMI_VFRMT_1920x1080p30_16_9    34

Note that 34 is the index corresponding to 4096x2160p24_16_9 in libhdmi/hdmi.cpp

**Comment by gabrielgagz** [comment] 2017-08-15 16:30
Well that's a great disocover, now the question is...should we modify the kernel or the lib sources?

**Comment by lbdroid** [comment] 2017-08-15 16:31
It may be a coincidence.

Its a pretty terrible EDID implementation.
It reads the EDID block, finds the index corresponding to that EDID block in msm_hdmi_modes.h, and then discards the timing information. Then userspace grabs that index and uses it to look up the timing, again from msm_hdmi_modes.h.

You would think that they would be smart enough to just take the timing from the edid and use that.

**Comment by lbdroid** [comment] 2017-08-15 16:58
I believe that it is a coincidence.

There is another possibility; your monitor may actually advertise that it supports a 4k mode. It is not uncommon for EDID data to be broken. The problem with the EDID implementation we have here is that it ignores what the monitor claims to be the optimal resolution (typically the panel's native timings), and instead goes by the order in gEDIDData[].

Alternatively, maybe your monitor really does support a 4k input resolution and downscales it to its native resolution, but the 4k output may be broken. Keep in mind that just because the chip supports 4k, and the kernel has code for it, doesn't mean that it ACTUALLY supports it. It could be a firmware option that razer didn't buy from qualcomm.

**Comment by lbdroid** [comment] 2017-08-15 17:02
There should be a line in logcat containing "parseResolution" followed by several that read "Mode[#] = #". I'd like to see that list for your monitor. If it contains a "Mode[#] = 131", then there is either a parsing bug in the kernel, or your monitor is claiming to support 4k.

**Comment by gabrielgagz** [comment] 2017-08-15 17:08
Yes i far i remember there's somehting like "DisplayModes" ... with all modes supported by the chip and the one selected by the TV. I'll test it again when i have some time in another tv, with all modes anabled.

**Comment by lbdroid** [comment] 2017-08-15 17:10
You don't need to reenable anything for that output. This output happens before the modes are validated against gEDIDData[].

**Comment by gabrielgagz** [comment] 2017-08-15 17:14
Yes, but i have a rom build compiled with a cropped libhdmi. I just need to know if edid works properly or not, or if it's that tv specifically. I know the output is always there...

**Comment by lbdroid** [comment] 2017-08-15 17:21
Well I can tell you that EDID definitely does NOT work properly. It is broken in two ways;

1) It ignores the resolution that the monitor flags as native, and instead picks the highest resolution that the monitor claims to support,
2) It ignores the timings that the monitor provides for the resolutions that it supports, and instead chooses its own timings based on the resolutions.

The same resolution can be obtained by using more than one set of timings, but a particular monitor doesn't necessarily accept all the different possible timings in order to produce that resolution.

Your monitor could very well be able to handle a 4k input, just not using the timings that qcom has defined.

So before you go and rebuild and reinstall, I'd like you to start it up on that same monitor and capture the kmsg and logcat. That output *should* be enough to determine where the setup is going bad.

**Comment by gabrielgagz** [comment] 2017-08-15 17:25
> It ignores the timings that the monitor provides for the resolutions that it supports, and instead > chooses its own timings based on the resolutions.

Probably this is the cause of flickerings. I'll take a look when i get home....

**Comment by lbdroid** [comment] 2017-08-15 18:58
Its possible. I was previously thinking that you meant flickering as having the screen going blank for a moment and then coming back. If its a continuous flickering, that may very well point to a timing issue.

**Comment by lbdroid** [comment] 2017-08-15 19:39
I think that in the very least, we probably should adjust the display hal so that it stops at a 1080p resolution as maximum, but without disabling the 4k modes altogether. We can do that in the getBestConfig() function at line 478. Instead of if (order > bestOrder), we can use if (order > bestOrder && order <= 27). That will make it stop at 1920x1080p30. The user will still have the option to set hw.hdmi.resolution to any value listed in msm_hdmi_modes.h that is also reflected in gEDIDData[].

**Comment by gabrielgagz** [comment] 2017-08-15 19:55
logcat | grep Display:

`08-15 16:48:32.343  1484  1594 I DisplayManagerService: Display device added: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1920 x 1080, modeId 4, defaultModeId 4, supportedModes [{id=1, width=640, height=480, fps=60.000004}, {id=2, width=720, height=480, fps=60.000004}, {id=3, width=1280, height=720, fps=60.000004}, {id=4, width=1920, height=1080, fps=60.000004}, {id=5, width=1920, height=1080, fps=50.0}, {id=6, width=720, height=576, fps=50.0}, {id=7, width=1920, height=1080, fps=24.0}, {id=8, width=1920, height=1080, fps=25.0}, {id=9, width=1920, height=1080, fps=30.0}, {id=10, width=1280, height=1024, fps=60.000004}, {id=11, width=800, height=600, fps=60.000004}, {id=12, width=1024, height=768, fps=60.000004}, {id=13, width=0, height=0, fps=Infinity}], colorMode 0, supportedColorModes [0], HdrCapabilities android.view.Display$HdrCapabilities@a69d6308, density 320, 320.0 x 320.0 dpi, appVsyncOff 7500000, presDeadline 12666666, touch INTERNAL, rotation 0, type BUILT_IN, state UNKNOWN, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
08-15 16:48:32.346  1484  1594 I DisplayManagerService: Display device changed state: "Built-in Screen", ON
`

**Comment by gabrielgagz** [comment] 2017-08-15 20:01
kmsg: https://pastebin.com/raw/sr4zfvKe
dmesg: https://pastebin.com/raw/EvacjpUf
logcat: http://pasted.co/edac3d9f

**Comment by gabrielgagz** [comment] 2017-08-15 20:17
As you see the only info i get from the logs, related to Display modes is in the top of logcat...

**Comment by lbdroid** [comment] 2017-08-15 20:27
Going to have to crank up the logging. Also the start of the kmsg is
clipped, try unplugging and replugging after boot and see what it spits out.

**Comment by gabrielgagz** [comment] 2017-08-15 20:43
Most of the logs are related to hdcp nothing useful on kmesg dmesg or logcat.

EDIT: Probably we have something here: https://pastebin.com/raw/zK2n8M2d

**Comment by lbdroid** [comment] 2017-08-15 23:08
It's trying to do something with modes 128-131. That means that something is asking for 4k modes.

Run this and post output;

cd /sys/devices/virtual/graphics/fb0
for FILE in *; do echo $FILE; cat $FILE; done

**Comment by gabrielgagz** [comment] 2017-08-16 00:56
edid_modes:
`1,2,4,5,16,31,17,32,33,34,137,135,136,128,129,130,131`

edid_3d_modes:
`131=`

modes:
`U:1920x1080p-0
U:1920x1080p-0
U:1920x1080p-2`

msm_fb_panel_info (probably here we should get something)
`pu_en=0
xstart=0
walign=0
ystart=0
halign=0
min_w=0
min_h=0`

vendor_name (ok):
`razer`

video_mode (probably this doesn't match?):
`16`

virtual_size (is this incorrect?):
`1920,2160`

I'm trying to understand where this modes ids (137,135,136,128,129,130,131) cone fronm...

**Comment by lbdroid** [comment] 2017-08-16 12:24
The virtual size is fine.
There are three possible sources of those modes >= 128;
1) the edid block it is using is hardcoded rather than read from the monitor,
2) the function that determines the list of modes is broken,
3) the monitor is actually claiming those modes.

What you might want to try, is connecting that monitor to a machine with a known working edid implementation and dumping its modes from there. For instance, running "xrandr --props" from a terminal on a linux machine running one of the open source graphics drivers (like a radeon or intel GPU) should be able to dump the list of modes, characteristics, and even include a dump of the raw edid block.

As an example output, this is for my laptop's internal display;
```
eDP-1 connected 1920x1080+0+1080 (normal left inverted right x axis y axis) 344mm x 193mm
	EDID: 
		00ffffffffffff0006afed3500000000
		001701049522137802d1159e59539b27
		1e505400000001010101010101010101
		010101010101783780b470382e406c30
		aa0058c110000018fb2480b470382e40
		6c30aa0058c110000018000000000000
		00000000000000000000000000000002
		000c33ff0e3c961b0d1c962020200041
	scaling mode: Full 
		supported: None, Full, Center, Full aspect
   1920x1080     60.05*+  40.04  
   1680x1050     60.00  
   1400x1050     59.98    60.00  
   1280x1024     59.95    60.02  
   1440x900      59.99  
   1280x960      60.00    59.99  
   1280x854      59.95  
   1280x800      59.96  
   1280x720      59.97  
   1152x768      59.95  
   1024x768      60.04    60.00    59.95  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   800x600       60.00    60.32    59.96    56.25  
   848x480       59.94  
   700x525       59.98  
   720x480       59.94  
   640x512       60.02  
   640x480       60.00    59.94    59.94  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05
```

You will notice that the "+" symbol identifies the native mode, the "*" symbol identifies the current mode. Any line indicating multiple refresh rates indicates that there are more than one set of timings available for that resolution.

**Comment by lbdroid** [comment] 2017-08-16 13:08
Actually, xrandr may add in some extra stuff as well.
Best solution may be to run this;
```
$ cd /sys/devices
$ find . | grep edid
./pci0000:00/0000:00:01.0/drm/card0/card0-DP-2/edid
./pci0000:00/0000:00:01.0/drm/card0/card0-eDP-1/edid
./pci0000:00/0000:00:01.0/drm/card0/card0-DP-1/edid
$ cat {one of those} | edid-decode
```

It will look something like this (same laptop internal monitor as last message above);
```
cat ./pci0000:00/0000:00:01.0/drm/card0/card0-eDP-1/edid | edid-decode
Extracted contents:
header:          00 ff ff ff ff ff ff 00
serial number:   06 af ed 35 00 00 00 00 00 17
version:         01 04
basic params:    95 22 13 78 02
chroma info:     d1 15 9e 59 53 9b 27 1e 50 54
established:     00 00 00
standard:        01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
descriptor 1:    78 37 80 b4 70 38 2e 40 6c 30 aa 00 58 c1 10 00 00 18
descriptor 2:    fb 24 80 b4 70 38 2e 40 6c 30 aa 00 58 c1 10 00 00 18
descriptor 3:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 4:    00 00 00 02 00 0c 33 ff 0e 3c 96 1b 0d 1c 96 20 20 20
extensions:      00
checksum:        41

Manufacturer: AUO Model 35ed Serial Number 0
Made week 0 of 2013
EDID version: 1.4
Digital display
6 bits per primary color channel
DisplayPort interface
Maximum image size: 34 cm x 19 cm
Gamma: 2.20
Supported color formats: RGB 4:4:4
First detailed timing is preferred timing
Established timings supported:
Standard timings supported:
Detailed mode: Clock 142.000 MHz, 344 mm x 193 mm
               1920 2028 2076 2100 hborder 0
               1080 1090 1100 1126 vborder 0
               -hsync -vsync 
Detailed mode: Clock 94.670 MHz, 344 mm x 193 mm
               1920 2028 2076 2100 hborder 0
               1080 1090 1100 1126 vborder 0
               -hsync -vsync 
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 2
Checksum: 0x41 (valid)
EDID block does NOT conform to EDID 1.3!
	Missing name descriptor
	Missing monitor ranges
```

Or could look something like this (composite external monitor);
```
cat ./pci0000:00/0000:00:01.0/drm/card0/card0-DP-2/edid | edid-decode
Extracted contents:
header:          00 ff ff ff ff ff ff 00
serial number:   22 f0 4e 31 01 01 01 01 1a 18
version:         01 04
basic params:    a5 30 1b 78 2a
chroma info:     eb f5 a6 56 51 9c 26 10 50 54
established:     a1 08 00
standard:        d1 c0 81 c0 81 80 95 00 a9 c0 b3 00 01 01 01 01
descriptor 1:    02 3a 80 18 71 38 2d 40 58 2c 45 00 dd 0c 11 00 00 1e
descriptor 2:    a2 6c 00 18 f1 38 2d 40 2c 58 45 00 ff ff 00 00 00 1e
descriptor 3:    00 00 00 fc 00 48 50 20 45 32 32 31 69 0a 20 20 20 20
descriptor 4:    27 4a 00 98 a1 00 2a 40 30 70 13 00 ff ff 00 00 00 1e
extensions:      00
checksum:        04

Manufacturer: HWP Model 314e Serial Number 16843009
Made week 26 of 2014
EDID version: 1.4
Digital display
8 bits per primary color channel
DisplayPort interface
Maximum image size: 48 cm x 27 cm
Gamma: 2.20
DPMS levels: Off
Supported color formats: RGB 4:4:4, YCrCb 4:2:2
First detailed timing is preferred timing
Established timings supported:
  720x400@70Hz
  640x480@60Hz
  800x600@60Hz
  1024x768@60Hz
Standard timings supported:
  1920x1080@60Hz
  1280x720@60Hz
  1280x1024@60Hz
  1440x900@60Hz
  1600x900@60Hz
  1680x1050@60Hz
Detailed mode: Clock 148.500 MHz, 477 mm x 268 mm
               1920 2008 2052 2200 hborder 0
               1080 1084 1089 1125 vborder 0
               +hsync +vsync 
Detailed mode: Clock 278.100 MHz, 255 mm x 255 mm
               3840 3884 3972 4120 hborder 0
               1080 1084 1089 1125 vborder 0
               +hsync +vsync 
Monitor name: HP
Detailed mode: Clock 189.830 MHz, 255 mm x 255 mm
               2560 2608 2720 2968 hborder 0
               1024 1025 1028 1066 vborder 0
               +hsync +vsync 
Checksum: 0x4 (valid)
EDID block does NOT conform to EDID 1.3!
	Missing monitor ranges
	Detailed block string not properly terminated
EDID block does not conform at all!
	Invalid detailed timing descriptor ordering
```
Note that the second example is actually a composite monitor, so the 3840x1080 and 2560x1024 modes are kind of "fake" and span two actual monitors.

Also note that the edid-decode command is (in Fedora) provided by the package xorg-x11-utils.

**Comment by lbdroid** [comment] 2017-08-16 13:25
The wikipedia article breaks down all the fields in the edid;
https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#EDID_1.3_data_format

**Comment by gabrielgagz** [comment] 2017-08-17 00:02
I think my laptop come with an mini hdmi to hdmi output, so i have to get a cable...

**Comment by gabrielgagz** [comment] 2017-08-31 22:48
`Extracted contents:
header:          00 ff ff ff ff ff ff 00
serial number:   20 a3 30 00 01 00 00 00 23 14
version:         01 03
basic params:    80 73 41 78 0a
chroma info:     cf 74 a3 57 4c b0 23 09 48 4c
established:     21 08 00
standard:        81 c0 81 40 81 80 01 01 01 01 01 01 01 01 01 01
descriptor 1:    02 3a 80 18 71 38 2d 40 58 2c 45 00 80 88 42 00 00 1e
descriptor 2:    1b 21 50 a0 51 00 1e 30 48 88 35 00 44 4a 21 00 00 1c
descriptor 3:    00 00 00 fc 00 48 44 4d 49 0a 20 20 20 20 20 20 20 20
descriptor 4:    00 00 00 fd 00 32 4b 0f 45 0f 00 0a 20 20 20 20 20 20
extensions:      01
checksum:        6c

Manufacturer: HEC Model 30 Serial Number 1
Made week 35 of 2010
EDID version: 1.3
Digital display
Maximum image size: 115 cm x 65 cm
Gamma: 2.20
Supported color formats: RGB 4:4:4, YCrCb 4:2:2
First detailed timing is preferred timing
Established timings supported:
  640x480@60Hz
  800x600@60Hz
  1024x768@60Hz
Standard timings supported:
  1280x720@60Hz
  1280x960@60Hz
  1280x1024@60Hz
Detailed mode: Clock 148.500 MHz, 1152 mm x 648 mm
               1920 2008 2052 2200 hborder 0
               1080 1084 1089 1125 vborder 0
               +hsync +vsync 
Detailed mode: Clock 84.750 MHz, 580 mm x 330 mm
               1360 1432 1568 1776 hborder 0
                768  771  776  798 vborder 0
               -hsync +vsync 
Monitor name: HDMI
Monitor ranges (GTF): 50-75Hz V, 15-69kHz H, max dotclock 150MHz
Has 1 extension blocks
Checksum: 0x6c (valid)

CEA extension block
Extension version: 3
40 bytes of CEA data
  Video data block
    VIC 01 640x480@60Hz 
    VIC 02 720x480@60Hz 
    VIC 04 1280x720@60Hz 
    VIC 05 1920x1080i@60Hz 
    VIC 16 1920x1080@60Hz (native)
    VIC 20 1920x1080i@50Hz 
    VIC 31 1920x1080@50Hz 
    VIC 17 720x576@50Hz 
    VIC 32 1920x1080@24Hz 
    VIC 33 1920x1080@25Hz 
    VIC 34 1920x1080@30Hz 
  Audio data block
    Linear PCM, max channels 1
    Supported sample rates (kHz): 48 44.1 32
    Supported sample sizes (bits): 24 20 16
    AC-3, max channels 7
    Supported sample rates (kHz): 192 176.4 96 88.2 48 44.1 32
    Maximum bit rate: 56 kHz
  Speaker allocation data block
  Vendor-specific data block, OUI 000c03 (HDMI)
    Source physical address 1.0.0.0
    DC_36bit
    DC_30bit
    DC_Y444
    Maximum TMDS clock: 225MHz
    Extended HDMI video details:
      3D present
      All advertised VICs are 3D-capable
      HDMI VIC 0 3840x2160@30Hz
      HDMI VIC 1 3840x2160@25Hz
      HDMI VIC 2 3840x2160@24Hz
      HDMI VIC 3 4096x2160@24Hz
      3D: Side-by-side (half, horizontal)
      3D: Top-and-bottom
      3D: Frame-packing
Basic audio support
Supports YCbCr 4:4:4
Supports YCbCr 4:2:2
1 native detailed modes
Detailed mode: Clock 74.250 MHz, 708 mm x 398 mm
               1920 2448 2492 2640 hborder 0
                540  542  547  562 vborder 0
               +hsync +vsync interlaced 
Detailed mode: Clock 74.250 MHz, 708 mm x 398 mm
               1920 2008 2052 2200 hborder 0
                540  542  547  562 vborder 0
               +hsync +vsync interlaced 
Detailed mode: Clock 74.250 MHz, 708 mm x 398 mm
               1280 1390 1430 1650 hborder 0
                720  725  730  750 vborder 0
               -hsync -vsync 
Checksum: 0x23 (valid)

`

**Comment by gabrielgagz** [comment] 2017-09-01 02:22
Something interesting here: 

[https://patchwork.kernel.org/patch/2846572/](url)
[https://github.com/gabrielgagz/android_kernel_razer_pearlyn/blob/cm-14.1/drivers/gpu/drm/drm_edid.c](url)

**Comment by lbdroid** [comment] 2017-09-01 15:02
That isn't intel-specific, it is universal.
And I don't think that says that 4k support is 3d-only. It says "3d capable".

So I guess the question is this; does your tv *actually* support 4k? Or is that a glitch?

**Comment by gabrielgagz** [comment] 2017-09-01 15:46
Actually, vendor only claims 1080p support as max resolution. I have to do more tests with my laptop, probably i should try to switch the tv to 4k, to see what happens. Also, i'll test the forge with all modes enableds in another tv, to se if edid is properly working.

**Comment by gabrielgagz** [comment] 2017-09-01 16:50
This is the chasis of my tv: https://es.scribd.com/document/350440108/Hisense-chasis-MTK5652-pdf (1080p), wiith a local brand. I don't really care aout the tv, i just want to find out if edid is working properly.
I'll do some test later in another of my tv's...

**Comment by lbdroid** [comment] 2017-09-01 18:59
I think its a software problem. I'm looking at the edid bytes, and there is no indication of any 4k mode in there.

**Comment by gabrielgagz** [comment] 2017-09-01 23:00
i cannot force 4k with my laptop, the limit is 1080p. 
xrandr

```
HDMI-1 connected 1920x1080+1366+0 (normal left inverted right x axis y axis) 1152mm x 648mm
   1920x1080     60.00*+  50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1280x1024     60.02  
   1280x960      60.00  
   1360x768      59.80  
   1280x720      60.00    60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
```

**Comment by gabrielgagz** [comment] 2017-09-02 00:04
Well i just test the Forge with all modes in one of my phillips tv (1080p) and guess what? Edid works properly...or this sh*tty tv is giving wrong edid info, or maybe 4k isn't really works on the 805...
I don't have a 4k to test...

**Comment by gabrielgagz** [comment] 2017-11-27 01:38
We should open a new issue related to edid. I'm closing this...

**Closed by gabrielgagz** 2017-11-27 01:38 UTC
